version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rails_demo_app:latest
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    volumes:
      - .:/rails
    command: ["./bin/rails", "server", "-b", "0.0.0.0"]
