steps:
  - label: ":docker: Build"
    plugins:
      - docker-compose#v3.7.0:
          build: app # Updated from 'web' to 'app'
          image-repository: index.docker.io/deanoloftwah/rails

  - label: ":ruby: Test"
    plugins:
      - docker-compose#v3.7.0:
          run: app # Updated from 'web' to 'app'
          command: ["bundle", "exec", "rake"] # Command as an array
