steps:
  - label: ":docker: Build"
    plugins:
      - docker-compose#v3.7.0:
          build: web
          image-repository: index.docker.io/deanoloftwah/rails

  - label: ":ruby: Test"
    plugins:
      - docker-compose#v3.7.0:
          run: web
          command: "bundle exec rake"